name: Android Integration Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter packages
        run: flutter pub get

      - name: Install patrol_cli
        run: dart pub global activate patrol_cli

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          disk-size: 4000M
          force-avd-creation: true
          emulator-build: latest

      - name: Run integration tests
        run: patrol test --target integration_test/app_test.dart
