name: Android Integration Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter packages
        run: flutter pub get

      - name: Install patrol_cli
        run: dart pub global activate patrol_cli

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v3
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          disk-size: 4000M

      - name: Add Android SDK platform-tools to PATH
        run: echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV && echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Run integration tests
        run: patrol test --target integration_test/example_test.dart
